### ISSUE TITLE
New myLink hardware supports more channels

### ISSUE THREAD

**Issue by scelfo** [bendews/smartthings-somfy-mylink#1]
I’m guessing you have a first generation myLink due to only supporting 5 devices. The new hardware (I think v2) supports up to 16 channels.

Would you want to extend your pattern to copy/paste variable names to add another 9 channels? If so I’d be happy to help contribute and send you a pull request.

**Comment by bendews** [comment]
Hey @scelfo, I do have a v2 MyLink but was keeping it down to 5 to keep it more straightforward, until I could figure out a good way to automatically discover the configured blinds. I haven't had any requests as of yet to increase the blind count but as you mentioned it is just a copy + paste job, so feel free to do a PR 😄 
I will also open a new GH issue for discovering the existing blinds on the controller and setting them up.

**Comment by scelfo** [comment]
Ah, that makes sense! I have 14 roller shades... so... I’ll just make a
pull request to go up to the full 16 that the v2 supports. Thanks for
starting this project, I was very sad when the installer first came and I
realized it wouldn’t easily integrate with SmartThings.

**Comment by scelfo** [comment]
sent https://github.com/bendews/smartthings-somfy-mylink/pull/3

**Comment by bendews** [comment]
Closing as PR has been merged, thanks again!
